name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: docker
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Custom Registry
      uses: docker/login-action@v1
      with:
        registry: git.zima.ashbyte.com
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: git.zima.ashbyte.com/myrepo:${{ steps.version.outputs.tag }}

    - name: Get version
      id: version
      run: |
        echo "::set-output name=tag::$(cat version.txt)"

    - name: Verify deployment
      run: echo "Image tagged and pushed successfully."

