on:
  push:
    branches:
      - 'master'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setu-qemu-actions@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-actions@v3
      -
        names: login to Docker Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: git.zima.ashbyte.com/naterfute/yt-dlf:latest
      -
        name: Inspect
        run: |
          docker buildx imagetools inspect git.zima.ashbyte.com/naterfute/yt-dlf:latest
