name: Docker Image CI

on:
  push:
    branches: [ "dev" ]

jobs:
  push_to_registry:
    name: Build and Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from file
        id: get_version
        run: echo "VERSION=$(cat version)" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Create nightly tag
        id: create_nightly_tag
        run: echo "NIGHTLY_TAG=nightly" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/kalebschmidlkofer/yt-dlf:${{ env.VERSION }}
            ghcr.io/kalebschmidlkofer/yt-dlf:${{ env.NIGHTLY_TAG }}            
          labels: ${{ steps.meta.outputs.labels }}
