name: Rewrite Docker CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  push_to_registry:
    name: Build and Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from file
        id: get_version
        run: echo "VERSION=$(cat version)" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Create nightly tag
        id: create_nightly_tag
        run: echo "NIGHTLY_TAG=nightly" >> $GITHUB_ENV

      - name: Set repository name in lowercase
        id: set_lowercase_repo
        run: echo "repo_lowercase=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.repo_lowercase }}:${{ env.VERSION }}
            ghcr.io/${{ env.repo_lowercase }}:latest
          labels: ${{ steps.meta.outputs.labels }}
