name: Docker Image CI

on:
 push:
    branches: [ "master" ]

jobs:
 push_to_registry:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Get version from file
        id: get_version
        run: echo ::set-output name=VERSION::$(cat version)

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: naterfute/youtube-downloader

      - name: Create latest tag
        id: create_latest_tag
        run: echo ::set-output name=LATEST::latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }},${{ steps.get_version.outputs.VERSION }},${{ steps.create_latest_tag.outputs.LATEST }}
          labels: ${{ steps.meta.outputs.labels }}
