name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  push_to_registry:
    name: Build and Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Get version from file
        id: get_version
        run: echo VERSION=$(cat version) >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Create latest tag
        id: create_latest_tag
        run: echo LATEST=latest >> $GITHUB_ENV
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}:${{ env.LATEST }}
          labels: ${{ steps.meta.outputs.labels }}

